# Generated by Django 6.0.2 on 2026-03-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='achievements',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='challenges',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
