# Generated by Django 6.0.2 on 2026-03-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_achievements_portfolio_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='challenges',
            field=models.TextField(blank=True),
        ),
    ]
