# Generated by Django 6.0.2 on 2026-03-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='achievements',
            field=models.TextField(help_text='Kết quả đạt được', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='challenges',
            field=models.TextField(help_text='Thách thức và giải pháp', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(help_text='Đường dẫn tới trang web của dự án', null=True),
        ),
    ]
