# Generated by Django 6.0.2 on 2026-03-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_image',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
