# Generated by Django 5.2 on 2026-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự hiển thị"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hiển thị"),
                ),
                (
                    "badge_icon",
                    models.CharField(
                        choices=[
                            ("developer_mode", "Developer Mode"),
                            ("language", "Language / Web"),
                            ("transform", "Transform"),
                            ("rocket_launch", "Rocket Launch"),
                            ("stars", "Stars"),
                        ],
                        default="developer_mode",
                        max_length=50,
                        verbose_name="Icon badge",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(max_length=100, verbose_name="Chữ badge"),
                ),
                (
                    "title_line1",
                    models.CharField(max_length=200, verbose_name="Tiêu đề dòng 1"),
                ),
                (
                    "title_line2_highlight",
                    models.CharField(
                        max_length=200, verbose_name="Tiêu đề dòng 2 (màu đỏ)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Mô tả ngắn")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="carousel/",
                        verbose_name="Ảnh nền slide",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Nếu upload ảnh thì để trống ô này",
                        max_length=500,
                        verbose_name="Hoặc dùng URL ảnh nền",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        default="Slide image",
                        max_length=200,
                        verbose_name="Alt text ảnh",
                    ),
                ),
                (
                    "btn1_text",
                    models.CharField(max_length=100, verbose_name="Nút 1 - Chữ"),
                ),
                (
                    "btn1_url",
                    models.CharField(
                        help_text="Ví dụ: /contact/ hoặc {% url 'contact:contact' %}",
                        max_length=200,
                        verbose_name="Nút 1 - URL",
                    ),
                ),
                (
                    "btn2_text",
                    models.CharField(max_length=100, verbose_name="Nút 2 - Chữ"),
                ),
                (
                    "btn2_url",
                    models.CharField(max_length=200, verbose_name="Nút 2 - URL"),
                ),
            ],
            options={
                "verbose_name": "Slide Carousel",
                "verbose_name_plural": "Slides Carousel",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hiển thị"),
                ),
                (
                    "badge_text",
                    models.CharField(
                        default="Chuyên gia giải pháp phần mềm",
                        max_length=100,
                        verbose_name="Chữ badge",
                    ),
                ),
                (
                    "title_main",
                    models.CharField(
                        default="IPSystem -",
                        max_length=200,
                        verbose_name="Tiêu đề chính",
                    ),
                ),
                (
                    "title_highlight",
                    models.CharField(
                        default="Chuyên gia",
                        max_length=200,
                        verbose_name="Từ nổi bật (màu đỏ)",
                    ),
                ),
                (
                    "title_suffix",
                    models.CharField(
                        default="Thiết kế Phần mềm",
                        max_length=200,
                        verbose_name="Phần còn lại của tiêu đề",
                    ),
                ),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "btn1_text",
                    models.CharField(
                        default="Tư vấn giải pháp",
                        max_length=100,
                        verbose_name="Nút 1 - Chữ",
                    ),
                ),
                (
                    "btn1_url",
                    models.CharField(
                        default="/contact/", max_length=200, verbose_name="Nút 1 - URL"
                    ),
                ),
                (
                    "btn2_text",
                    models.CharField(
                        default="Tìm hiểu thêm",
                        max_length=100,
                        verbose_name="Nút 2 - Chữ",
                    ),
                ),
                (
                    "btn2_url",
                    models.CharField(
                        default="/about/", max_length=200, verbose_name="Nút 2 - URL"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hero/",
                        verbose_name="Ảnh hero (bên phải)",
                    ),
                ),
                (
                    "hero_image_alt",
                    models.CharField(
                        default="Phát triển phần mềm chuyên nghiệp",
                        max_length=200,
                        verbose_name="Alt text ảnh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
    ]
