# Generated by Django 6.0.2 on 2026-05-21 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("images_1", models.ImageField(null=True, upload_to="news/images/")),
                (
                    "types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.newstype"
                    ),
                ),
            ],
        ),
    ]
