# Generated by Django 6.0.2 on 2026-05-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="NewsDetail",
        ),
    ]
