# Generated by Django 6.0.2 on 2026-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("doanh-nghiep", "Doanh nghiệp"),
                            ("thuong-mai", "Thương mại điện tử"),
                            ("quan-ly", "Quản lý nội bộ"),
                            ("khac", "Khác"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="samples/")),
            ],
        ),
    ]
