# Generated by Django 6.0.2 on 2026-05-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="samples/"),
        ),
    ]
