# Generated by Django 6.0.2 on 2026-05-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0002_alter_sample_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="file",
            new_name="image_1",
        ),
        migrations.AddField(
            model_name="sample",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="samples/"),
        ),
        migrations.AddField(
            model_name="sample",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="samples/"),
        ),
    ]
